version: "3"
services:
  builder:
    build: ./builder
    volumes:
      - .:/work
    working_dir: /work
  superbuilder8:
    build:
      context: ./builder
      args:
        build_as_root: "yes"
    volumes:
      - .:/work
    working_dir: /work
  tester8:
    image: almalinux:8
    volumes:
      - .:/work
    working_dir: /work
